version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgresqlDb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./flaskBE
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgresqlDb: